---
name: Verify Requirements

on:
  workflow_dispatch:
  schedule:
    # Runs every Monday at 8:00 UTC
    - cron: '5 8 * * *'

jobs:
  upgrade:
    uses: DLRSP/workflows/.github/workflows/verify-requirements.yaml@v1.15.8
    secrets: inherit
